site_name: "Grind Documentation"
site_author: "NoPainAndGain"
site_url: ''

theme:
    name: 'material'

repo_url: https://bitbucket.org/nopainandgain/grind
repo_name: 'BitBucket private Repository'
markdown_extensions:
    - admonition:
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.superfences:


pages:
    - Home: 'index.md'
    - Research:
        - 'Ideas': 'research/ideas.md'
        - 'SDL Init': 'research/sdl.md'
        - 'Functional tests': 'research/test.md'
        - 'GL Context': 'research/glcontext.md'
        - 'Display EGL Object': 'research/display.md'
        - 'Display Server': 'research/display_server.md'
    - EGL:
        - 'eglGetConfig': 'egl/egl_get_config.md'
