[package]
name        = "grind-egl"
version     = "0.1.0"
authors     = ["Jean-Sebastien BEVILACQUA <realitix@gmail.com>", "Robert KING"]
publish     = false
description = "EGL proxy fro Grind"

[lib]
name        = "EGL"
crate-type  = ["cdylib"]

[dependencies]
khronos = "0.1.1"
libc = "0.2.16"
