[package]
name = "glsltranspiler"
version = "0.1.0"
authors = ["Jean-Sebastien BEVILACQUA <realitix@gmail.com>", "Robert KING"]
publish = false
description = "GLSL Transpiler"

[lib]
name = "glsltranspiler"
crate-type = ["lib"]
